### ISSUE TITLE
Incompatible with gauge 0.3.2

### ISSUE THREAD

**Issue by hakito** [getgauge/gauge-visualstudio#102]
When opening a .spec file the following error dialog pops up:

```
Gauge - Critical Error Occurred

Unable to launch Gauge Daemon. Ensure that
1. Gauge is installed.
2. Gauge.exe is available in PATH
```

The reason is that the only [argument passed to gauge.exe is `--daemonize`](https://github.com/getgauge/gauge-visualstudio/blob/ed7ea1ba5d9b3f818f5b85a8179c92d6f5253c1d/Gauge.VisualStudio.Core/Helpers/GaugeDaemonHelper.cs#L161).

It seems gauge.exe 0.3.2 also requires *specs* as the 2nd argument.

The error message is also confusing as gauge.exe actually is installed and in the PATH, but the start of the process fails.

**Comment by sriv** [comment]
Gauge does not require the second argument when running in `daemon` mode. The `daemon` mode is invoked by IDEs to make use of the API that Gauge offers.

In your particular case, my guess is that the process start failed due to some reason. Are you running VS as administrator? If not could you please try it? 

My theory is - gauge is installed in `C:\Program Files\Gauge\` and if Visual Studio isn't able to invoke `gauge.exe`. This definitely calls for better error reporting mechanism.

**Comment by hakito** [comment]
We inspected the call of gauge.exe with process monitor. Visual Studio does start the process gauge.exe correctly. We tried to start gauge 0.3.2 from the command line without the *spec* argument and it also failed. With the *spec* argument it worked.

We also tried the same with the latest 0.2 gauge and there was no *spec* argument nescessary.

**Comment by sriv** [comment]
Thanks for the research. We shall take a deeper look at this, my gut says we do not need the `specs

**Comment by kashishm** [comment]
Could you please confirm if it is a `spec` or `specs` directory and please share the output of `gauge --daemonize` command?

**Comment by hakito** [comment]
Sorry for the typo above. It's of course *spec_s_* when  creating the project using `gauge --init csharp`. But of course if you rename the *specs* folder it can be anything else.

Calling `gauge --daemonize` writes the following to the console:

`Got a kill message. Killing runner.`

...and returns with errorlevel 2.

**Comment by sriv** [comment]
Please try Gauge-VisualStudio [v0.2.1](https://visualstudiogallery.msdn.microsoft.com/dd8ea767-aa75-4771-98f4-6c8a9055ca92)? We've introduced logging the failure reason.

On your troubleshooting, 

`gauge specs --daemonize` seems to work because it is just running `gauge specs` i.e. gauge discards the `--daemonize` flag. The order of arguments is significant, in the sense that the specs directory should be the last argument and all flags should precede it.

The correct syntax to run Gauge as a daemon would be:

`gauge --daemonize specs`

Now this uncovers a different issue, i.e. gauge assumes `specs` to be your directory when running as a daemon. (Refer to your other issue getgauge/gauge#302). Thanks for reporting this.

I will keep this issue opened, since once getgauge/gauge#302 is fixed, the VS plugin should pass the specs directory explicitly.

**Comment by hakito** [comment]
I can confirm it works now.

**Comment by sriv** [comment]
@hakito , thanks for confirming!
