### ISSUE TITLE
No tests discovered with Gauge plugin and Visual Studio 2015 (Update 1 or Update 2)

### ISSUE THREAD

**Issue by WonkiDonk** [getgauge/gauge-visualstudio#112]
* Install Gauge
* Install csharp plugin with: `gauge --install csharp`
* Create a new folder with: `mkdir temp`
* Create new blank Gauge project with: `gauge --init csharp`
* Open `temp.sln`
* Build solution
* Expected: Visual Studio Test Explorer will show tests
* Actual: Visual Studio Test Explorer shows no tests

## Output from Tests
`------ Discover test started ------`
`========== Discover test finished: 0 found (0:00:00.0291383) ==========`

## Output from Gauge
`[Debug] Opening Gauge Daemon for Project : temp,  at port: 1000`
`[Debug] Opening Gauge Daemon with PID: 3256`
`[Debug] PID: 3256 ready, waiting for messages..`
`[Info] Request API for Specifications`
`[Info] Specifications: [Specification Heading]`
`[Debug] Adding TestContainer: C:\Workspace\temp\specs\example.spec`
## Environment
I am able to reproduce this issue on:
* Windows 8.1 with Visual Studio 2015 Update 2 Enterprise (reproduced by all 5 developers on the team)
* Windows 10 with Visual Studio 2015 Update 1 Professional

**Comment by sriv** [comment]
Can confirm this on my side.

**Comment by WonkiDonk** [comment]
Thanks, @sriv. If you have an idea on where to start or can point me in the right direction, I don't mind picking this up and resolving it. My team is really keen to adopt Gauge, but we're reticent to do so without the ability to debug our tests.

**Comment by sriv** [comment]
@WonkiDonk - We certainly appreciate all the help we can get! 

I notice that this issue occurs on VS 2015, with Gauge-VisualStudio 0.2.1, and is quite intermittent. In my case, there was a parse error on the specs, that caused the tests to not be discovered.

Can you please try:
- run `gauge specs` for the same project on command prompt to ensure that the tests are running without any parse errors?
- There is some refactoring on the test runner, that will be available in the next release. Can you please give the latest nightly build of VS-2015 a quick shot, and see if it is any better?

If you still have the issue, could you check `logs\gauge.log` and `logs\api.log` to see if there is any additional information that can help troubleshoot?

If you are interested in looking deeper, you could checkout the code, run Gauge-VisualStudio under the Experimental Instance of VS, and debug the test runner.

**Comment by sriv** [comment]
The last line of the previous comment isn't useful at all, sorry about that. If you are interested in the code behind the test explorer integration, here is a braindump of what's happening:

- Visual Studio launches two child processes (`vstest.discoveryengine.exe` for test discovery and `vstest.executionengine.exe` for test execution). This is important because if you need to debug the test runner, you need to attach the debugger to these processes to ensure that the breakpoint is hit.
- Gauge-VisualStudio has a `TestRunner` [project](https://github.com/getgauge/gauge-visualstudio/tree/master/Gauge.VisualStudio.TestAdapter) [Note that this is different from the live version]. Your logs indicate that the [`TestContainerDiscoverer.TestContainer`](https://github.com/getgauge/gauge-visualstudio/blob/master/Gauge.VisualStudio.TestAdapter/TestContainerDiscoverer.cs#L78) property is being accessed by the VS Test Explorer.
- Gauge-VisualStudio makes an [API request](https://github.com/getgauge/gauge-visualstudio/blob/master/Gauge.VisualStudio.TestAdapter/TestContainerDiscoverer.cs#L86) to `gauge.exe` which runs as a background daemon for every Gauge project opened via Visual Studio. 
- This API request [asks](https://github.com/getgauge/gauge-visualstudio/blob/master/Gauge.VisualStudio.Model/Specification.cs#L52) Gauge core to give it a list of specifications and scenarios.

In this case, it looks like the communication with Gauge Core, discovery of Specifications etc is working fine, since you do see `Adding Test Container` being logged.

If you could please try the two options (running via command line, and trying the nightly) and see if it makes any difference, we can decide on how to polish this up with proper messages. Else, this could be an actual issue.

**Comment by WonkiDonk** [comment]
I assigned this issue to a member of my team, @mbalmer2016, this morning. He identified and resolved the issue already. The issue was caused by some hard-coding of tool version number paths into a few classes. If you already have VS2013 installed on your computer then you will be unlikely to see the issue; the issue only occurs if you have only ever had VS2015 installed. He hot fixed by switching the version number and built a copy of the VSIX to unblock our team. Our hot fix now only works in VS2015.

I'll ask @mbalmer2016 to re-work the changes to refactor out the platform version information so that it works properly on VS2013 and above. I'll get a copy of the contributor's agreement completed and see if I can get him to submit a pull request tomorrow.

We did have some trouble initially building the project. The build script provided has a parameter (`$gaugelibversion$`, I think) baked into a few of the `package.config` files. We had to manually enter the latest package version number to get this working. Is this something that the build script should be doing, or were we doing something wrong?

**Comment by sriv** [comment]
The `$gaugelibversion$` should not be part of the build, I see that this error is happening while doing a `nuget restore` on `Gauge.VisualStudio.sln`. 

The `$gaugelibversion$` parameters are placeholders in `packages.config` that are part of the templates, supposed to be substituted with the latest version in the target user's project, when (s)he creates a new Gauge project via Visual Studio.

I will be excluding them out of the project, thanks for pointing it out. In the meantime, have you or @mbalmer2016 had any luck with the pull request?

**Comment by sriv** [comment]
Have pushed https://github.com/getgauge/gauge-visualstudio/commit/6aed22ad9de9786a64895f3fa494d71f5bd064e7. Please pull and you should not see the `$gaugelibversion$` errors in build.

**Comment by manavghaigithub** [comment]
Hey - Is this issue resolved. I am looking for clear documentation on how to debug in Visual Studio 2017.
We are using VS Studio 2017 with .Net Core framework. I couldn't find clear steps on how to debug my code when running through Gauge. Can you please point me to steps and guidelines on how to debug code when using Visual Studio 2017?

Gauge version: 1.0.2
Commit Hash: b4288bb
Plugins-------
csharp (0.10.5)
dotnet (0.1.0)
html-report (4.0.6)

**Comment by sriv** [comment]
Visual Studio + Gauge + .NET Core is discussed here: https://github.com/getgauge/gauge/issues/1288
