### ISSUE TITLE
VS Extension is not compatible to latest gauge csharp plugin

### ISSUE THREAD

**Issue by rkumarrb** [getgauge/gauge-visualstudio#137]
It seems current VS Extension is not compatible with gauge csharp plugin. it expects at least 0.6.0 version.

![image](https://cloud.githubusercontent.com/assets/6379299/17151243/f88c941a-5340-11e6-9457-a0343d08d12f.png)

**Comment by sriv** [comment]
Hi - this isn't an issue with Gauge-VisualStudio. There is a new release of Gauge-CSharp runner (0.9.0) which has some (potentially) breaking changes, since we released a few new features. The message indicates that you need to use Gauge.CSharp.Lib [v0.6.0](https://www.nuget.org/packages/Gauge.CSharp.lib/) in your Gauge project. 

Please do a nuget update in your project to have Gauge.CSharp.Lib v0.6.0 and verify the execution.

**Comment by rkumarrb** [comment]
Thank you. I will try to get library 0.6.0 and use it. Thank you for your help.
