### ISSUE TITLE
Versioning Issue

### ISSUE THREAD

**Issue by adman666** [getgauge/gauge-visualstudio#195]
### Expected behavior
The VS plugin should load successfully.

### Actual behavior
I recieve the following error: 
There was an error deserializing the object of type Gauge.VisualStudio.Core.GaugeVersionInfo. Encountered unexpected character 'D'.

### Steps to reproduce
1. Install the latest version of gauge and the c# plugin
2. Run Visual Studio
3. Observe the error message : There was an error deserializing the object of type Gauge.VisualStudio.Core.GaugeVersionInfo. Encountered unexpected character 'D'.

### Version Information

VisualStudio Version and Edition  : Microsoft Visual Studio Enterprise 2015 - Version 14.0.25431.01 Update 3
Gauge VisualStudio Plugin Version : Gauge.VisualStudio   1.0

C:\WINDOWS\system32>gauge -v
[DEPRECATED] This usage will be removed soon. Run `gauge help --legacy` for more info.
Gauge version: 0.9.0

Plugins
-------
csharp (0.10.1)
html-report (4.0.1)
xml-report (0.2.0)

In addition I pulled the repo and tried to build it, it fails with the same error so I assume you have not allowed for the additional characters in the version numbers. The plugin version is reported as 0.1.0.1 internally which I assume will be a problem. Your tests cases do not cover this scenario.

**Comment by zabil** [comment]
Thanks for reporting this @adman666 
We'll be releasing a fix soon.

**Comment by BugDiver** [comment]
@adman666 We have released a new version of this plugin with fix.
Feel free to reopen the issue if the issue still exists.

**Comment by olegderid** [comment]
@BugDiver, please, reopen the issue it reproduces with Visual Studio 2015 Pro x64, with the following stacktrace:

![image](https://user-images.githubusercontent.com/272698/29603348-9116fce4-87ec-11e7-82ee-324ba004d3c0.png)

Error: There was an error deserializing the object of type Gauge.VisualStudio.Core.GaugeVersionInfo. Encountered unexpected character 'D'.

Stacktrace:
 <description>LegacySitePackage failed for package [GaugePackage]Source: 'System.Runtime.Serialization' Description: There was an error deserializing the object of type Gauge.VisualStudio.Core.GaugeVersionInfo. Encountered unexpected character 'D'.
System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type Gauge.VisualStudio.Core.GaugeVersionInfo. Encountered unexpected character 'D'. ---&gt; System.Xml.XmlException: Encountered unexpected character 'D'.
   at System.Xml.XmlExceptionHelper.ThrowXmlException(XmlDictionaryReader reader, XmlException exception)
   at System.Runtime.Serialization.Json.XmlJsonReader.ReadAttributes()
   at System.Runtime.Serialization.Json.XmlJsonReader.ReadNonExistentElementName(StringHandleConstStringType elementName)
   at System.Runtime.Serialization.Json.XmlJsonReader.Read()
   at System.Runtime.Serialization.XmlReaderDelegator.Read()
   at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReader

**Comment by BugDiver** [comment]
@olegderid It works perfectly fine for me with gauge@0.9.1 and gauge-visual-studio plugin version 0.3.1. Could you please check if you have installed the latest version of the plugin?
The latest version of the plugin can be found [here](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1071478.GaugepluginforVisualStudio).

**Comment by olegderid** [comment]
@BugDiver , the gauge release is the latest as well as the plugins are. after further digging the issue is caused by the fact that standard output is not sanitized before  passing it through the XML serialization:
https://github.com/getgauge/gauge-visualstudio/blob/54fb941a0cf7ff9905d0136c6871bbfaa9a0bbe5/Gauge.VisualStudio.Core/GaugeService.cs#L170

The quirk is that the workstation where the issue is reproduced had the GAUGE_ROOT instead of the new one GAUGE_HOME environmental variable configured. As you can notice below the [DEPRECATED]... warning causes the stack-trace error - _"System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type Gauge.VisualStudio.Core.GaugeVersionInfo. Encountered unexpected character 'D'. ---> System.Xml.XmlException: Encountered unexpected character 'D'.":

$ gauge --version
[DEPRECATED] This usage will be removed soon. Run `gauge help --legacy` for more info.
Gauge version: 0.9.1
....

**Workaround:** After changing the GAUGE_ROOT to GAUGE_HOME the Visual Studio plugin was loaded properly.

The issue will get reproduced in case there is a warning in the gauge console, thus the impact is low.
