### ISSUE TITLE
Individual Tags should be highlighted as a part of Syntax highlighting

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-visualstudio#236]
**Expected behavior**
Tags should be highlighted as given in the image below

<img width="151" alt="tags" src="https://user-images.githubusercontent.com/6310197/41211247-a6ebe1c2-6d53-11e8-879f-2f73658e7d3b.png">

**Actual behavior**
The highlight is incomplete

<img width="189" alt="tags_partial_highlight" src="https://user-images.githubusercontent.com/6310197/41211277-d455c592-6d53-11e8-8b13-c4edfabab287.png">

**Version**
```
Gauge version: 0.9.9.nightly-2018-06-01
Commit Hash: 812f26e

Plugins
-------
csharp (0.10.4.nightly-2018-05-29)
```
VS - gauge.visualstudio-latest.nightly-2018-06-06

**Comment by sriv** [comment]
The tags are being highlighted, just a different style. 

By design, gauge-visualstudio does not dictate the styles, rather it uses the theme's style of `literal`. Ref: https://github.com/getgauge/gauge-visualstudio/blob/master/Gauge.VisualStudio/Classification/Types.cs#L53.

In this case, VS2017's default theme seems to be using this style. We should not aim for exact styles, since the colour, font styles etc are inherited from the theme, allowing the users to change themes.
