### ISSUE TITLE
Executing single test case multiple times and displays multiple output for same in IDE

### ISSUE THREAD

**Issue by uzmar** [getgauge/gauge-visualstudio#70]
when selected option Test->Run-> All Test 

<img width="1147" alt="screen shot 2015-09-03 at 5 16 50 pm" src="https://cloud.githubusercontent.com/assets/10433272/9657590/1c3e8c52-5260-11e5-886b-20b52b89dd42.png">

**Comment by sriv** [comment]
Seems like multiple test cases (of same name and description) are added. One scenario where this happens is when you save a `spec` document.

This is because #51 required VS to listed to document saved event.

Need a way to clear/refresh/replace tests in a test explorer. Will continue investigation.

**Comment by sriv** [comment]
getgauge/gauge#204 should fix the api, but the plugin should also handle this.

**Comment by sriv** [comment]
Still happens, when editing tags. Need to investigate
