### ISSUE TITLE
report doesn't show all results when execute all specs from IDE

### ISSUE THREAD

**Issue by uzmar** [getgauge/gauge-visualstudio#72]
run more than 1 spec by IDE and check results in report

**Comment by sriv** [comment]
Here is why this happens:

- When multiple tests are selected from the VS Test explorer, and executed, each of them run the specs individually using a separate instance of Gauge.exe. Ref [here](https://github.com/getgauge/gauge-visualstudio/blob/master/Gauge.VisualStudio/TestRunner/TestExecutor.cs#L33).

- This causes subsequent tests runs to overwrite the last execution reports.

Potential solution:
- Design the report to have an append feature (long-term)
- Pass a group of tests to the GaugeRunner, so that all of them run at the same time. This has dependency on https://github.com/getgauge/gauge/issues/165. 

The tradeoff: if we fix this bug before we address https://github.com/getgauge/gauge/issues/165, it will break the execution progress reported, since Gauge-VS will not receive updates on execution progress.
