### ISSUE TITLE
No support for Visual Studio 2015?

### ISSUE THREAD

**Issue by MattFenner** [getgauge/gauge-visualstudio#81]
Just downloaded gauge for the first time and found that it has no support for Visual Studio 2015 which is quite annoying.

Is there plans to port the VS 2013 visual studio extension to VS 2015?
Has anyone made an unofficial or beta port yet?

**Comment by sriv** [comment]
Yes, VS-2015 is there in our radar, but it's a bit slow on progress. You can see [a few issues related to VS-2015](https://github.com/getgauge/gauge-visualstudio/labels/VS-2015).

AFAIK - there is not progress on VS-2015, beyond this codebase, so I don't think a port exists. 

If you are interested in contributing, please read the [contributing guidelies](http://getgauge.io/contribute/) and feel free to fork.

**Comment by MattFenner** [comment]
I know this is a difficult question, but any idea of expected completion date?

I am currently researching different tools for doing automated testing in our company. Currently gauge looks the best except there is no support for VS2015 which is what our devs are using.

**Comment by sriv** [comment]
I don't want to commit to something that could be misleading, but we are working on these issues, it's just that there are some things in the core and C# runner that are taking priority at the moment.

Glad to see the interest in Gauge. And we **do** want VS-2015 support, but unfortunately, not all the VS libraries/APIs that we use to build the Gauge VS plugin work well with 2015, and certain features need to be re-written. I know this is disappointing, but that's the sad reality.

FYI - currently, the VS plugin is version locked to prevent users from installing it on VS-2015, because quite a few things are broken. If you need to compile a VS-2015 version of the current code you would need to compile it after modifying [the vsixmanifest file](https://github.com/getgauge/gauge-visualstudio/blob/master/Gauge.VisualStudio/source.extension.vsixmanifest#L14)

**Comment by MattFenner** [comment]
I know you don't want to commit to anything. But would you expect to have something done before say mid 2016? or are the issues so serious that you dont see it happening anytime soon.

I would be happy to wait say 6 months. but longer than that would unfortunately mean i would have to find another tool. And i would rather make that decision now rather than going down the wrong path now.

**Comment by sriv** [comment]
The timeline has more to do with the amount of effort that would need to go in to get this done. It isn't technically complex, given where we are at with VS-2013 support. Compared to the effort to code for VS-2015 support, testing it on VS-2015 while ensuring VS-2013 does not regress is going to be huge. 

Would contributing towards this plugin be an option for you? I intend to start off a branch/repo with some basic stuff setup, and list areas that would require work, provided there is some interest in the community to help achieve this. We can definitely help new members get started on this.

**Comment by sriv** [comment]
@MattFenner - Just pushed a few commits that should bring Gauge to VS 2015. We should be releasing to VS gallery shortly.

**Comment by iaacek** [comment]
Hi, any update on VS gallery release of Gauge VS2015?

**Comment by sriv** [comment]
@iaacek, We are still working on it. There are a couple of things holding this back

- testing on multiple VS flavours, i.e. community
- there is an observation that uninstalling VS 2013 sometimes causes the gauge plugin to not work on 2015, there isn't an issue logged yet.

**Comment by sriv** [comment]
Just an update - still working on it. Most authoring parts seem to work. Test discovery is broken on VS-2015. Am investigating it, but it isn't the easiest task around, to be honest, and there seems to be no documentation on VS about this.

**Comment by sriv** [comment]
v0.2.0 [is released](https://visualstudiogallery.msdn.microsoft.com/dd8ea767-aa75-4771-98f4-6c8a9055ca92) with VS-2015 support. Feel free to check it out and report any issues/features.

Closing this issue.
